name: Deploy Project (Fed Creds)

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
# manually trigger a workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
      deployments: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}      
    steps:

    # ############################################################
    #                   Build Project
    # ############################################################

    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/marketplace/actions/setup-node-js-environment
    - uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
    
    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build


    # ############################################################
    #                   Google Cloud Config 
    # ############################################################

    # https://github.com/marketplace/actions/authenticate-to-google-cloud
    - name: 'Auth gcloud using federated credentials'
      uses: google-github-actions/auth@v1
      with:
        project_id: ${{ vars.GCLOUD_PROJECT_ID }}
        service_account: ${{ vars.SVC_ACCOUNT_EMAIL }}
        workload_identity_provider: ${{ vars.PROVIDER_URL }}    
  
    # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.GCLOUD_PROJECT_ID }}

    - name: Push Files to GCP Storage bucket
      run: |
        gcloud storage cp -r build/* gs://${{ vars.BUCKET_NAME }}